### ISSUE TITLE
Make Corner and Make End buttons stay "pressed" after being clicked on

### ISSUE THREAD

**Issue by xan2622** [Jrome90/Make_Corner_End#5]
Hi. 

I have a suggestion about the two buttons in the toolbar: 

I noticed that, as soon as you click on them (but ofc, after selecting two vertices on your mesh first), the state of these buttons stay "pressed". 

![Capture d’écran 2020-12-27 090731](https://user-images.githubusercontent.com/1732773/103166596-fa942480-4823-11eb-8169-6ffbf681314a.png)

In order to use these buttons once again, the user has to: 
1. click on the box-select tool (to reset the state of the "last used button")
2. click on the button of his/her choice (Make End or Make Corner)

It makes perfectly sense to have these buttons on this toolbar (they are very accessible this way) but I think that these buttons should reset their neutral state after being pressed (and Blender should revert to the previously used tool, most of the time: the Box-select tool).

---

Note: As you can see on the screenshot above, some add-ons add a separator between their icons in the toolbar. It would be nice if your add-on had that too.

**Comment by Jrome90** [comment]
It is supposed to change the tool to select box after clicking it. 
![make_corner_toolbar_button](https://user-images.githubusercontent.com/11284891/103167802-20e5a000-47e3-11eb-910d-cfc0183fc907.gif)

**Comment by Jrome90** [comment]
This has been fixed.
