### ISSUE TITLE
Disabling addon w/ "Add the additional tools to toolbar" checked w/o restarting throws error; must close blender

### ISSUE THREAD

**Issue by ChimeraReyat** [Jrome90/Make_Corner_End#6]
This causes two kinds of traceback errors. First happens when disabling the addon:

![image](https://user-images.githubusercontent.com/7088788/128832987-5b0345fb-eb18-4abc-baa8-b4628cf438ba.png)

The second, likely related to the first, happens when trying to re-enable the addon:

![image](https://user-images.githubusercontent.com/7088788/128833060-8d9e5d45-dce4-472f-8070-6afe6b5f32c5.png)

If I were to guess, a class isn't being unregistered at the right time? A little weird; I know the feature is experimental though. Hopefully this isn't a hard fix.

**Comment by Jrome90** [comment]
thanks, I'll look into it.

**Comment by Jrome90** [comment]
> If I were to guess, a class isn't being unregistered at the right time? A little weird; I know the feature is experimental though. Hopefully this isn't a hard fix.

Close.
Classes weren't being unregistered after the exception was thrown.
The exception was caused by unregistering the tools that were not yet registered. 
I wrapped it all in a try except block with a finally clause.

That should fix it.
